language: java
dist: trusty
jdk: oraclejdk8
cache: false
env:
  global:
  - EX_GLOBAL=${TRAVIS_BUILD_DIR}
services:
- mysql
addons:
  sonarcloud:
    organization: eusurvey
    token:
      secure: "$SONAR_TOKEN"
before_install:
- mysql -e "CREATE DATABASE eusurveydb;"
- mysql -e "CREATE DATABASE eusurveyreportdb;"
- mysql -e "CREATE USER 'eusurveyuser'@'localhost' IDENTIFIED BY 'eusurveyuser';"
- mysql -e "CREATE USER 'eusurveyruser'@'localhost' IDENTIFIED BY 'eusurveyruser';"
- mysql -e "GRANT ALL PRIVILEGES ON eusurveydb.* TO 'eusurveyuser'@'localhost';"
- mysql -e "GRANT ALL PRIVILEGES ON eusurveyreportdb.* TO 'eusurveyruser'@'localhost';"
- mysql -e "GRANT EVENT ON eusurveydb.* TO 'eusurveyuser'@'localhost' IDENTIFIED BY 'eusurveyuser';"
- mysql -e "SET GLOBAL event_scheduler = ON;"
- mysql -e "SET GLOBAL log_bin_trust_function_creators = 1;"
- mysql -e "SET GLOBAL TRANSACTION ISOLATION LEVEL READ COMMITTED;"
install: true
jobs:
  include:
  - stage: Tests
    script:
    - mvn clean test -Denvironment=oss
    - sonar-scanner
  - stage: Deployment
    script:
    - mvn clean install -Dmaven.test.skip=true -Denvironment=oss
