version: "3.7"
services:
  db:
    container_name: db
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=password
    volumes:
        - ./mysql:/docker-entrypoint-initdb.d/:ro
    command: --lower_case_table_names=1 --transaction-isolation=READ-COMMITTED
    networks:
      - eusurvey_network
  server:
    build: server
    container_name: eusurvey_server
    image: tomcat-eusurvey-server
    volumes:
      - type: bind
        source: ~/eusurveytemp
        target: /eusurveytemp/
    ports:
      - "8080:8080"
      - "8886:8886"
    depends_on:
      - db
    networks:
      - eusurvey_network
  maildev:
    container_name: maildev
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - eusurvey_network
networks:
  eusurvey_network:
    driver: bridge 