version: "3.7"
services:
  db:
    container_name: db
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=password
    volumes:
        - ./mysql:/docker-entrypoint-initdb.d/:ro
    command: --lower_case_table_names=1 --transaction-isolation=READ-COMMITTED
  server:
    build: server
    image: tomcat-eusurvey-server
    volumes:
      - type: bind
        source: ~/eusurveytemp
        target: /eusurveytemp/
    ports:
      - "8888:8080"
      - "8886:8886"
    container_name: tomcat_eusurvey_server
    depends_on:
      - db